// File generated manually from google-services.json and GoogleService-Info.plist.
// Normally this would be auto-generated by `flutterfire configure`, but we're
// creating it by hand so the project compiles immediately after cloning.
//
// If you ever need to regenerate (e.g., after adding a new Firebase service),
// run: dart pub global activate flutterfire_cli && flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Provides platform-specific Firebase configuration extracted directly
/// from the google-services.json (Android) and GoogleService-Info.plist (iOS)
/// files that live in the project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not configured for this Firebase project. '
        'Add a web app in the Firebase console and update this file.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for '
          '${defaultTargetPlatform.name}. Add support in firebase_options.dart.',
        );
    }
  }

  // Values pulled from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBodyUcD2YEIRpNeXCg4skTMAGyM5em8M0',
    appId: '1:455341952888:android:171da32e231e5baf7a828d',
    messagingSenderId: '455341952888',
    projectId: 'quick-shorts-24b14',
    storageBucket: 'quick-shorts-24b14.firebasestorage.app',
  );

  // Values pulled from ios/Runner/GoogleService-Info.plist
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnCm8LEmhzlHHLgKTeSp0Gh-tYfNZpLvk',
    appId: '1:455341952888:ios:3c6f909a819dfaf57a828d',
    messagingSenderId: '455341952888',
    projectId: 'quick-shorts-24b14',
    storageBucket: 'quick-shorts-24b14.firebasestorage.app',
    iosBundleId: 'com.example.quickShorts',
  );
}
